# Generated by Django 2.2.13 on 2020-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
