# Generated by Django 2.2.13 on 2020-09-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='pic',
            new_name='logo',
        ),
    ]
